version: '3.7'
services:

  #app
  app:
    logging:
      driver: none
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      - VIRTUAL_HOST=web-test.test
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app_network

  #nginx
  web_server:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./data/Certificates:/etc/nginx/certs
    networks:
      - app_network

  #mariadb
  database_server:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
      - ./web_test.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: web_test
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
